"use client";

import { useState } from "react";
import { fetchAiDiagnosis } from "../lib/api.ts";
import { firstSentence } from "../lib/render.ts";
import { selectEvent } from "../lib/use-selection.ts";
import type { AiDiagnosisReport, EvidenceReport, FailureReport, GraphOverview } from "../lib/types.ts";

interface Props {
  overview: GraphOverview;
  failure: FailureReport;
  evidence: EvidenceReport;
}

type AiState = "idle" | "loading" | "done" | "error";

export function WhyStrip({ overview, failure, evidence }: Props) {
  const [aiState, setAiState] = useState<AiState>("idle");
  const [aiReport, setAiReport] = useState<AiDiagnosisReport | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);

  async function generateAiAnalysis() {
    setAiState("loading");
    setAiError(null);
    try {
      setAiReport(await fetchAiDiagnosis());
      setAiState("done");
    } catch (err) {
      // Surface the failure plainly: the local template must never stand in
      // as a model reply, so on error there is no interpretation at all.
      const msg = err instanceof Error ? err.message : String(err);
      setAiError(
        msg.includes("HTTP 503")
          ? "AI analysis is unavailable on this server (no model API key configured)."
          : msg.includes("HTTP 502")
            ? "The model call failed or its reply violated the diagnosis format — nothing was stored."
            : `AI analysis failed: ${msg}`,
      );
      setAiState("error");
    }
  }

  const aiBlock = (
    <>
      <div className="ai-row">
        <button type="button" onClick={generateAiAnalysis} disabled={aiState === "loading"}>
          {aiState === "loading"
            ? "Generating…"
            : aiState === "done"
              ? "Regenerate AI analysis"
              : "Generate AI analysis"}
        </button>
        {aiState === "error" && aiError && (
          <span className="hint" role="alert">
            {aiError}
          </span>
        )}
      </div>
      {aiState === "done" && aiReport?.sections && (
        <div className="ai-block">
          <h3>Model interpretation — not evidence</h3>
          <p className="hint">
            Generated by {aiReport.model ?? "unknown model"}
            {aiReport.generated_at ? ` at ${aiReport.generated_at}` : ""}. May be wrong;
            verify every claim against the DAG and inspector.
          </p>
          <p>{aiReport.sections.diagnosis}</p>
          {aiReport.sections.evidence.length > 0 && (
            <ul>
              {aiReport.sections.evidence.map((line, i) => (
                <li key={i}>{line}</li>
              ))}
            </ul>
          )}
          <p className="muted">{aiReport.sections.limitations}</p>
        </div>
      )}
    </>
  );

  if (!overview.failure_event_id) {
    return (
      <section className="card why" aria-labelledby="why-heading">
        <div className="why-head">
          <h2 id="why-heading">Why did it fail?</h2>
          <div id="failure-info" className="muted" />
        </div>
        <p id="why-text" className="why-text">
          This dataset contains no events, so there is nothing to diagnose.
        </p>
        <div className="causal-path" id="causal-path" aria-label="causal path">
          <span className="path-label">Causal path: </span>
        </div>
      </section>
    );
  }
  const roleEntries = Object.entries(failure.roles ?? {});
  const byId = new Map(overview.nodes.map((n) => [n.id, n]));
  const sliceSize = overview.nodes.filter((n) => n.in_failure_slice).length;
  const info = failure.is_fallback
    ? "Failure status: fallback — no ground-truth selector matched, so the last event is shown positionally, not as a causal claim."
    : `Failure status: resolved via ${failure.method} · ` +
      `${roleEntries.length} role${roleEntries.length === 1 ? "" : "s"} resolved` +
      (failure.unresolved_roles.length > 0
        ? ` · unresolved: ${failure.unresolved_roles.join(", ")}`
        : "");
  const ordered = roleEntries
    .map(([role, hits]) => ({ role, node: byId.get(hits[0]?.event_id) }))
    .filter((s) => s.node)
    .sort((a, b) => (a.node?.logical_seq ?? 0) - (b.node?.logical_seq ?? 0));

  return (
    <section className="card why" aria-labelledby="why-heading">
      <div className="why-head">
        <h2 id="why-heading">Why did it fail?</h2>
        <div id="failure-info" className="muted">
          {info}
        </div>
      </div>
      <p id="why-text" className="why-text">
        {firstSentence(evidence.summary) || "No evidence summary available."}
      </p>
      <div className="causal-path" id="causal-path" aria-label="causal path">
        <span className="path-label">Causal path: </span>
        {ordered.length > 0 ? (
          ordered.flatMap((s, i) => {
            const btn = (
              <button
                key={s.role}
                className="path-step role"
                type="button"
                title={s.node?.label}
                onClick={() => s.node && selectEvent(s.node.id)}
              >
                {s.role}
              </button>
            );
            return i > 0
              ? [
                  <span key={`arrow-${s.role}`} className="path-arrow">
                    →
                  </span>,
                  btn,
                ]
              : [btn];
          })
        ) : (
          <span className="path-note muted">
            No ground-truth roles — showing the {sliceSize}-event structural slice instead.
          </span>
        )}
      </div>
      <details className="tech">
        <summary>Full technical explanation</summary>
        <pre>{(evidence.summary || "(no evidence)").trim()}</pre>
      </details>
      {aiBlock}
    </section>
  );
}
